### PR TITLE
Added support for optional multilingual books

### PR DESCRIPTION
**Pull request by deathbeam**
Usage:

``` json
"pluginsConfig": {
    "edit-link": {
        "multilingual": false
    }
}
```

Default when omitted is `true`.

### CODE REVIEW

**Comment by zhaoda** [comment]
I did that too, or remove the html lang attribute.

**Comment by sks** [comment]
+1 for this PR :)

**Comment by zhaoda** [comment]
@sks https://plugins.gitbook.com/plugin/editlink

**Comment by rahul286** [comment]
@deathbeam I think default should be false

Even better would be ability to detect automatically correct option.

**Comment by hannesvdvreken** [comment]
:+1: waiting for this to be available cause current edit links are broken.

**Comment by SamyPesse** [comment]
This can easily be fixed using the latest gitbook API: https://github.com/GitbookIO/gitbook/blob/master/theme/javascript/state.js#L15

I'm going to commit a fix for this.

**Pull request closed without merging**
