### PR TITLE
Fixed error when there was no label set in config

### PR DESCRIPTION
**Pull request by aschempp**
Sorry about that. I had that fixed in my local code but somehow it did not get committed :-(

Also a question: Currently, if you do define a label for some but not all languages of your book, that could result in an error or strange output. Do you think we need to cover that? If so I'll add it to this PR.

### CODE REVIEW

**Comment by rahul286** [comment]
I don't need to work on other languages, so my opinion should not matter on this.

**Comment by rahul286** [comment]
May be @aniav can add provide some inputs. 

She contributed - https://github.com/rtCamp/gitbook-plugin-edit-link/pull/2

**Comment by aniav** [comment]
I will check that in our multilanguage book and post any updates if any errors occur :)

**Comment by rahul286** [comment]
@aniav Thanks. :-)

Please check with v1.4.1 (latest as of now).

**Pull request merged**
