### PR TITLE
Fix support for multilingual books

### PR DESCRIPTION
**Pull request by SamyPesse**
Close #10

### CODE REVIEW

**Comment by SamyPesse** [comment]
@rahul286 Let me know if you're okay with this PR, and I'll merge it and publish a new version.

**Comment by hannesvdvreken** [comment]
:ship:

**Comment by rahul286** [comment]
@SamyPesse I do not know about multiligunal aspects of gitbook. Never used it.

Please go ahead as you see it fit.

**Comment by SamyPesse** [comment]
Done :) released as `2.0.1`

**Comment by hannesvdvreken** [comment]
:+1: thanks!

**Pull request merged**
