### PR TITLE
Adapt to GitBook 2.5.x

### PR DESCRIPTION
**Pull request by SamyPesse**
This PR adapts the plugin to the latest APIs of GitBook.

Since the `engine` is changed in `package.json`, old version of GitBook will always fallback to the previous version of `edit-link`.

### CODE REVIEW

**Comment by rahul286** [comment]
@SamyPesse Thanks for pull request. :-)

I added you as collaborator on repo. Is it fine for you to merge and release on own?

I will be happy to add as contributor on NPM. 

I am traveling for next 2 weeks, so I won't be able to work on this project for a while. Sorry.

**Comment by SamyPesse** [comment]
Ok thanks :+1: 

Let me know when you added me on NPM and I'll publish a new version.

**Comment by rahul286** [comment]
Thanks. I am having hard time with NPM today.

Added you via commands:

```
rahul286:gitbook-plugin-edit-link/ (master) $ npm owner ls                                                 
rahul286 <rahul.bansal@rtcamp.com>
rtcamp <admin@rtcamp.com>
samypesse <samypesse@gmail.com>
```

And then also as contributor in package.json. 

But it's not showing you on - https://www.npmjs.com/package/gitbook-plugin-edit-link

Are you able to publish now?

Sorry for this mess but gitbook plugins are only NPM modules I created.

**Comment by rahul286** [comment]
@SamyPesse I can see you https://www.npmjs.com/package/gitbook-plugin-edit-link 

Was it NPM cache or something I missed?

**Comment by SamyPesse** [comment]
I published a new version of `gitbook-plugin-edit-link`, everything worked fine :beers:

**Comment by rahul286** [comment]
Thanks :beers: 

btw if you have some time please check https://github.com/rtCamp/gitbook-plugin-edit-link/pull/8

**Pull request merged**
